Update HTML and rename DataLab to Bennett Institute
ebmdatalab/covid_trials_tracker-covid pull request #39
Opened 2022-03-25 12:16 UTC by tomodwyer

- Fix markup and run prettier on HTML
- Update "DataLab" to "Bennett Institute" in text

2022-03-25 13:05 UTC, ghickman approved these changes

2022-03-30 10:08 UTC, madwort requested changes
search-replace errors in email addresses

2022-03-30 10:08 UTC, madwort commented on docs/about/index.html
> +            <a href="mailto:ebmBennett Institute@phc.ox.ac.uk">Get in touch</a>.
this looks wrong

2022-03-30 10:09 UTC, madwort commented on docs/about/index.html
> +          >ebmBennett Institute@phc.ox.ac.uk</a
also here

2022-03-30 10:09 UTC, madwort commented on docs/about/index.html
> +          href="https://github.com/ebmBennett Institute/covid_trials_tracker-covid"
also here

2022-03-30 10:21 UTC, madwort approved these changes

2022-03-30 10:24 UTC, merged